modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="examplemod"
version="0.1.0"
displayName="Example Mod"
authors="thebluetropics"
description="An Example Mod"

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="1.16.5"
    ordering="NONE"
    side="BOTH"
