modLoader="javafml"
loaderVersion="[0,)"
license="MIT"
issueTrackerURL="https://github.com/thebluetropics/forge-example-mod/issues"

# Example Mod
[[mods]]
modId="%mod_id%"
version="%version%"
displayName="Example Mod"
logoFile="assets/%mod_id%/icon.png"
description="An example Forge mod"
authors="thebluetropics"
displayTest="MATCH_VERSION"
displayURL="https://github.com/thebluetropics/forge-example-mod"

# Forge
[[dependencies."%mod_id%"]]
    modId="forge"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

# Minecraft
[[dependencies."%mod_id%"]]
    modId="minecraft"
    mandatory=true
    versionRange="1.20.6"
    ordering="NONE"
    side="BOTH"
